
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test
  - jshint
  - jstest

build:
  script: gradle assemble
  stage: build

test:
  script: gradle check
  stage: test

jshint:
  script:
    - cd web
    - npm install
    - grunt jshint
  stage: jshint

jstest:
  script: grunt jasmine:api
  stage: jstest
